ENV_VARS = {
    "LOOKER_BASE_URL": "BASE_URL_ENV_VAR",
    "LOOKER_CLIENT_ID": "CLIENT_ID_ENV_VAR",
    "LOOKER_CLIENT_SECRET": "CLIENT_SECRET_ENV_VAR",
    "LOOKER_PROJECT": "PROJECT_ENV_VAR",
    "LOOKER_GIT_BRANCH": "BRANCH_ENV_VAR",
    "LOOKER_PORT": "8080",
    "LOOKER_API_VERSION": "3.0",
}
