TEST_BASE_URL = "https://test.looker.com"

ENV_VARS = {
    "LOOKER_BASE_URL": TEST_BASE_URL,
    "LOOKER_CLIENT_ID": "CLIENT_ID_ENV_VAR",
    "LOOKER_CLIENT_SECRET": "CLIENT_SECRET_ENV_VAR",
    "LOOKER_PROJECT": "PROJECT_ENV_VAR",
    "LOOKER_GIT_BRANCH": "BRANCH_ENV_VAR",
}
